difficulty = 8
persisted_chain_path = "saved_files/"
block_reward = 100
db_path = "saved_files/bd/caramuru_main_db.db"
max_block_size_kb = 1
miner_wallet_seed_path = "keys/miner_wallet.json"
miner_wallet_password = "miner123"
max_mining_attempts = 3